apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi #   REPLACE_ME 👈 警告：Jellyfin 的元数据和图片缓存非常大，建议 10G 起步