---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-db-secret
  namespace: media
spec:
  encryptedData:
    postgres-password: AgAx8jr2Uxjvj+0ykrV52rgK+Lgl8BICikFbkz/tPLkQhB6L1KvwYG0F9Sl/vbDJ9aPVb/dWvXbnS0NwCJuy1ou9qGGuz8ADrA/k1Ls2L8E8ovW8J7hwFCExde4jmG8CpKfZCHY5AXzYA303OHyxPo67KvxfPpy6AjNhkxx+qD7MswLGtCZI+RRZxhT8MTvrvdLmAmXeBcmdEfd/Ew6B8nf9tdi1efjFtxBwLjy6ygGps9LMVwREn2R/YjTUyPFKIxpSVCFBMGGa2i/iACsJuri0RWMyfgX1KM+YaFkqIPu7VHRQAc4XTAzuf80SThpTaFAxdjHfrfqTiUoniQOMUl1VVs1LZ5pOq1etHjUMeQTamzF52HRwcf+CE0AJ0k4eEzVXN/tOz1Pi7CP5hsSHfS4UC4qaRyLlVsCRU0xaB5soJuEy6KhC6tcInifGLU2Tee93sxqEyf2qevHBfmNZ2a0rdDZU/X+dmU8F/LVhZor0eyVkwiThqwf2e23l8o1hLoE/ackTW0Kx9Kp6ib85jqsBecg9tOzvw5NrNn46CJxGMsiF/0PWY13HyShJh3/ftI1phBjCpQ1PqVd6hEThm7z7tlYdrSyo00Tvx3UJujUvRdWYCHF3ig72Bq4xzQ7c/TO53ulmNuAQ7WYppTl11migbnRfv4hgn8dGrBmbz0hnm+TohPHXEu6AAK8mB9eqIPOL1bzrYpZmUc0=
  template:
    metadata:
      name: media-db-secret
      namespace: media
    type: Opaque
