---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-db-secret
  namespace: media
spec:
  encryptedData:
    postgres-password: AgAAvVxKXrAuPSVE5KIb43td3K+6OtTkWUwsD3DiseyYFp42iYUUUx8JYW/+K4IVsMG95gKGJ+t/YDYyosFl0qTk6DvBeDSznqaWCa9KKh8MZ0looUmDOGGoJTzHr1Eyu92EgKT+qXccH/UjzCv7vjfmRHN5MVg0Dda2Pyi91EfGZco/ze4Anc7E4Ebne1AiID9nH1s4bhlpBorPljTfDlOkSBBVfoeeM5ibyCqjEJt3mzhGjLZpRQsv/WeIuTNWAtCXwgdl/PNLfa+b/7bixtpHlLwmZXB/KmuQIPCMp1J4pROjzZWQuV8j3Y7L8iuV89B4EvJuTeal9pCWddkOqkeInF1jbeCEyaYnBWgXkY8c+F16d2FBLATcni0e8/SxfE1fmEqIfwLpv9poUoFwd13hzaPEIbuwWOtXIAyCcwv9vlkUxMEoQUfcmt/zvM1dkiJb6bvEIiLty4bGohXgmZxGwr8c7A6GLcNaAMz6+IQm1R9aG8Nm8s/lfTKd9FKfSQsl895JjLeJUJHuBZUwIKB4NsqUMRFY1usS79hcqWEdfVJZoshFLoE6LLreVEVtTQT94Sc9ByK41bMePgUU08xTdWoY0zX9XtGPEGF6kbytOxwoE1KpnBvWc93u/DUbQaP6T2+qIi/xN7j/ctbm7Zyx4VVs7xtOv3+HFdu3gcdmHejMu8qkU2fyLZY8i8Q1LwU9wIS0dx4a3T0=
  template:
    metadata:
      name: media-db-secret
      namespace: media
    type: Opaque
