apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
      annotations:
        # 绑定前面创建的 Macvlan 网络
        k8s.v1.cni.cncf.io/networks: media/macvlan-direct
    spec:
    # 新增下面这块 DNS 配置，跳过 K8s CoreDNS
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 223.5.5.5         # 阿里云 DNS
          - 114.114.114.114   # 114 DNS
          - 8.8.8.8           # Google DNS
      nodeSelector:
        kubernetes.io/hostname: k3s-master-01
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        ports:
        - containerPort: 8080
          name: webui
        - containerPort: 52000
          name: bt-tcp
        - containerPort: 52000
          name: bt-udp
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Shanghai"
        - name: WEBUI_PORT
          value: "8080"
        - name: TORRENTING_PORT  
          value: "52000"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /media 
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qb-config-pvc
      - name: data
        nfs:
          server: 10.0.10.10    #   REPLACE_ME 提交成自己的nfs共享的ip地址
          path: /mnt/nfs/media  # REPLACE_ME 提交成自己的nfs共享的media目录