apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-pvc
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M  #  REPLACE_ME 根据你实际使用的大小替换 1G 足够