# infrastructure/argocd/patch-argocd-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  # 语法：$<独立密码箱的名字>:<密码箱里的字段名>
  webhook.github.secret: "$argocd-github-webhook-keys:github-secret"