# infrastructure/argocd/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argocd-server # 🎯 修正：直接修改官方原生的名字
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.10.53 
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server