# infrastructure/argocd/webhook-secret.template.yaml (本地填完后加密，千万别提交这个模版！)
apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-webhook-keys  # 我们自己建的独立密码箱
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd # ⚠️ 官方文档要求：必须带这个标签！
stringData:
  github-secret: "你的超强接头暗号" # REPLACE_ME 替换你的密码 注意使用kubeseal加密后还原