---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-github-webhook-keys
  namespace: argocd
spec:
  encryptedData:
    github-secret: AgBwOVFZMghLjKTwI6YOMyq01vah5TPnQwr1UNazlpsbelD0sAEWBGkvighqYNJhFqK/TqfOku/ylC5YM7b0P7qbiyATdiPNfoohlrDGAqXIF54KIYUTdfNsfojwgLg4SfIfpxZe1wlCbL0HQUP+sSgC42rwB8+8dY5iGhv0HavqOSXp7a/fL4xbyhyvJw/zduLVuyJn6WGDKXbOlpu9j0vOsqGOdOgVHAJy9+ESUqgl3Qq6MhVCL6eTBvWGSopZifRmQrA6q0HR+0xNjAXoA+X4rsrc94kjMySpMofN1jR6ZLj2JRkJ7WUhPJu21LElFF+Sl+UENkkZBUizVTd2Mg+B985I1HZoCic4qNj/0ezQM8ZBqdN7s3xjjDoRvbiJfWc1iGcgWjex7Du/qyOQ8T1JsxXRwCeXaLYPv0jH1UPDQIVs7owwfZBUovySNMq3CGX1+vQUdTYn5ysYj9j1nTOT0mCfKhs8Ok31Eq4JPhMpzQcf6T/wclYH7OB5JeWqbPhcmiCw/P3rtZ0qE1IXkGXJzuzt5AAq+beDgDP4JkGra6qHvhBA/domCw0DmOTWqGhktOD/WGftzCzsOaIx3w68n9CaEeadopnCTRanN1LyjqzQT5mDcpyUELePx9iWnnf+GEB++GocBvsLrn9abelhcrciLDyUs3B95+X7T0qxj4mN4jJCQySON0BkJld+hLlXw4q6fM7Pc21vrxx+negOw4Xd+iEbIKLRuDGSpeRpW2bVpvO054aVWIce8w==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-github-webhook-keys
      namespace: argocd
