---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-github-webhook-keys
  namespace: argocd
spec:
  encryptedData:
    github-secret: AgBTbSVLN23cQjvEMjibWnvcjBLCyzbdhwpdlaLG27SpTm7zhFPOu8HS8P69Bph0U8+nbglrQolfTOltdW45zCyvsT1rR8FiTXUL/nWVxQSwNHqz4rq7htY2fW69tWTO8dyfrauxbC9fHbJz5PHsAqRKo3YzKQcgzQHOWZQC5dvpB6CQdKOC0yxZSApVLzOgsCwLiDWBPzGXkyStD5YzHrlmrwSBJLH6twX4T8BDl9Sk3GViAKvDG2i+3PduMYF0hGXHMXcyf89+mvqYZPqN/KCaXyeuzbZWWcjacPkQcBaBFDkmt3ZioHpaDGoyV5/HTGhuGQvtnIg/orcULYDTlzxnaeVXMs3vtY8aPEgBsztNV4WivFe0TNrhfuAe40fr0Aj8Oku/RJLr8mr4LeuTBn+NM9A9yR0BLbkgHvdH8GEtmY9JU8XHYUTnvVUZ1kVlPBhKSfZVzHDtug631toryas9I0iwQt1AG2V9QyV08nU9+rkqiSLN7ZRA9sp/gj9XY81Obd+3HBG7O17gES5aEFw9OOenyn4j4uKAtnWtsz8R1vQun/lBoRk7le/PRnCCj8YQqoE0gCOh5VkbRLsSWWR/fcqEA3zz6OGKxR7iCR7oTYaSb5zNLKuygFthadywIVmDqyBO0f21sykE9pv8ZMQxYQnOqSAltgUhWOYKX+Hk2qSxRCi9ZlZkIKIsJDkWJx3SN5WDYrIkwUHabXlg0yNdZttrGCuNH7siiS0Hga+c6fgUmuJmkzhXWL36vw==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-github-webhook-keys
      namespace: argocd
