apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc-longhorn
  namespace: database
spec:
  storageClassName: longhorn # 明确指定分布式存储
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M  #  REPLACE_ME 请根据实际情况填入 1G足够