apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: database
type: Opaque
stringData:
  # 在这里写明文，K8s 和 kubeseal 会自动处理 base64
  email: "<你的邮箱>" #  REPLACE_ME 替换为你的真实邮箱
  password: "<你的密码>"  #  REPLACE_ME 替换为你的真实复杂密码