---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: database
spec:
  encryptedData:
    email: AgCI9WuyO4m7SuAj+jebsUrMJLQNIBGab/NLr+7WQErJSiP7CylepOoacvJ6YWJ1ui5FGTexcOH0e6vCR3oiLMKXybnQMtpiOovp44Z9sTGO6M6to7jbZTZUsB5MEPzIW84v7mOtQFcZPth9HLE8QXpjcpTbxeXL0LDXHbQvZCWddxTTSc6W3MTormZ+6KfP+0oPqHm+8PyrKjOMFmw73hUVndVedASy4wEW23hjcjGb4f8aLKRRLe4SUPVZc87Ar0P7XxTkhwv0MDHC5SzOA75ZvKhWTdG8lwUDEsafM0MsaP8DmM8fMmOWHZfUjJjVTkUWfG3b9nysRf4AJikJgwSxJKhvIb9OJAKmGiceIO6jtxztu7higihWtAld+QRZuW+1TVlSgCD1xlqBLQEtOKhU1fJCWXldygrV7NgRqyCoqKT77akY3TQL4ViJV9VLm3sY01s+U4ZJFHcbHR0JBzxEFhRFw9aX3vjUmlFONCnyjuyYepJRkYhSYq1SjzjkceB3QVpmdSqqM09W+NnP1S1Lzhdrno7xhMlvnWK7hLgHMn/e1aGz1pHOdYdqODfZruM7q5Goi1sd60jtTP6StX5mCvGKfRjbKY3XuDATmXv56N4OXIkB/pJ4hD0Wmv8rYPxf6sZjN8U3r4Dj7e1C+ZDXXBscZRmJtFAEg33YDI6SWoUWAXeIz6j+pFsuf37BPRJjlc0YnrjFWp9alpdBs3uv8o4uxZ4=
    password: AgCdORxOFF40fh8M5n8yEQG/y/8T17UMDNUx3CIr/gw+A54G6z7WRRnA6WhFHiLOKY+wOwYQwhAeKKsBEliEJlOXC4dPU1wHZCx0CNgmf+b6+NmcsM+6H4aR003J9HofvPo5FG6uphYCsiEyFupPu4cPPbeWxIhUKcrLUTV7IxAWuOFxqbP0483AtJtJWltlXyZ+QEINN+SpjrMdKLHQMZGCwi0NUMXTYRpcD8Mm6IkaLsmL+I1uohWcJjeEd/A9a+826QVtgMwVOlKVHHjVScSENrZrcJiFAP0zMMhamWJCcoCtfyRy4L1h2YlIm4j1JzYVe8J0Bnd4+ASbE+0oKfiDelWD0j7vhvLozKPboR0o1bP1qFipJPLfR+Z2CVaC90AYNpZbXUkxoGQCV7o0A/GTDIXxmCuLqb9N5v6BxpS/XPgHNC8/kOe50xvWg6CmAFowGdMryMhyBREZ34ZwxzaBadeDpClHXHJiQ48WMfvsUzKRNqUZ9U6XGpMVrGOJHgMan/X+J/W85yDyo+SDZM92x/3y6cQ5EcAOnxu/Cbb478f7Ik7qGckOShQqfp8y7rHtzc3v40M0Sl1BLOgBCqxx3zcNRizweCLdQaZstSFDQ6bDq3kbeInDaiOCpl9hhaH6WG5Cbys9b+BkiebtXTP93vNL19tFbPDs4m8V/ORobqsEP1Wl+gky7/tjhoq+qocpdm6UwDwC3tE=
  template:
    metadata:
      name: pgadmin-secret
      namespace: database
    type: Opaque
