---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: database
spec:
  encryptedData:
    email: AgCNjY+7hW4+L++cbOsvsrm3Tydh4ZwTxsEkvQI8y3tFJ7L8CjKwlHHDvt7bI5cs5Z4jtHDiLmHl38vCdQPD20WTDqcjaLwTS5tkL6lJIzWNxHUayRwZBjP3jxJBZnTUYgvzaxSBsu4pSOQY5mbMgUSnmUdqgJRPOc9hRwvdM6uVbRNpGgkAysBRYG0Wy6TlZWYALNMO+R4wHcrOrEbNe4WO/N1WoxxnYtMlF/ghsP361uwXZ7kHxDywu9o8gxzpFrZvFCSBVHxDWi96iZDe4a9uVnfsDFDvQjbkvmSG9RccD3GBiFePIdClatJ3iNGpY0SvLwI45sqMtnqsWcmQMU2wQOYlFrlulY+Q0r9Ja4UozImEAthq6SW1ob4T6lhCYpLxyKW1YVQHpDYP1QU8ZciowrlaU8LqwMzXnj1get5Pxk7OMRWEEOHeEIFHt23081rzhNPoy+Gi+BR+JgJ5QdGne8vXq4d4lBg4X+LEU47PLjl/JhlNIYsqz5pZ7ztEmomgXNw48BmiyQjXiWxznWvJPkj2YV0TooHskvGO6fo5PNmhLbxBKISYPxA4SrrzBgBpNixsiKw30RZ0sb0YkxFHIZ+smh958pywzSZ65QZbZM1dyJRYujZH3sv8uhzuScjFSd3cWfcbD6Ak0rwfPuVfyU1qMD31TV21L/d31rBC4b99nhT0Mp0nJw/m0hhmzTXfeAX45fkAtMHTxfNi8u/5cCeLXoM=
    password: AgBPi6HGtMr7h+jVd5Eqae0EJuhEsnylP1yQ6+tjFKIAmD70uYm8/nzc5usbnbFuj5wSJIfFse16PIJJdBJvrpzw6J5+RTRP0d67fNX9EdhNPOIldzDsnXuLuqYh5pVRyFdGdz+CC0jwXvDuynrcg/apDvz2NBegYs3Gx2C+hxPtc4RPcBwB97BOgBb/hKNATaVg1LPs9KSmmAM7g0YCAq45EMRtxo+dHYoTD9x5oSp9HKGCFVKIdod4My9RPHmB7tj2dvwZckdHhufWBgqCQ6hLIqHgSbVZZqrPcV0hybM0GVftVWV829vR7+p62RZN6gvyKqcwlRt6fm70trSf3OiJIn8oZIN4VppL/Ss/c0kb8xKa4peW7r0HS73JVfBaeqJ4OUskyH8ss4RzjSYevguiKeQWOhh2BOHRAdl5BpDze8Qm6prVTqvoAycFE9k/pPRj3p6wbw9wK3JrkvFiVQdai5C4xFCLwVyKZdk1LQMKIMJZNhGdQQi5vmNntgxOzijqGvEkfRSgxM+xecrJmQmORx5gqYmlLjxn50HYjsTO5SXrzTDQuxnB3Xs99JbdJk4GTUMj78/9pec37faUZFHHYErGtCJqolPzDMTq7UdOfGOEGxS0V+mwuqXMhlvluZSQFRhYIAGEJTKqps9HLs+AdJMufVWBnoi9Rq/u8KgKNLzpVEYVrx3HQa5eMPtk9hMPQz62+tD/oa8=
  template:
    metadata:
      name: pgadmin-secret
      namespace: database
    type: Opaque
