# 1. 定义 ExternalName 类型的 Service (不需要 Endpoints)
apiVersion: v1
kind: Service
metadata:
  name: google-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: www.google.com # 直接填入外部域名

---
# 2. Traefik 路由规则
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: google-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`google.k3s.besthomelab.tech`)
      kind: Rule
      services:
        - name: google-external
          port: 443
          scheme: https
  tls: {}