apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: pve-external-ts
  namespace: traefik
spec:
  fallback:
    endpoints:
      - url: https://10.0.0.50:8006 # 直接写外部 PVE 地址
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.k3s.besthomelab.tech`)
      kind: Rule
      services:
        - name: pve-external-ts # 引用上面定义的 TraefikService
          kind: TraefikService
  tls: {}