apiVersion: v1
kind: Service
metadata:
  name: pve-external-proxy
  namespace: traefik
spec:
  type: ExternalName
  # 虽然官方建议这里写域名，但直接写 IP 在 Traefik 环境下是完全通的
  externalName: 10.0.0.50
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.k3s.besthomelab.tech`)
      kind: Rule
      services:
        - name: pve-external-proxy # 引用上面的别名服务
          port: 8006               # PVE 的端口
          scheme: https            # 告诉 Traefik 后面是加密的
  tls: {} # 继续白嫖你的正式证书