---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAaOEMWTPHF5ByalHN/Zud+8F/v6WJWPQXk3ZQVCBZCtMPS8tm7JDiYfpQOUUVmUsZh67ImOgvCihcePg0np22qfausrmZIOHalwWsDsMbx8aAfh9H8E2OqsJNfKGbGriMEEtaGABzLMm01a9HyNPcUUrtwrm3Qs7a10vWSyEZEubSFCwl3vDB0NCdcATbYnCyeIdUAhOqVIBbOq7OFrPsUi308+yt0VXya9n3dNJi6pC2tifZyJJ6Uo2Kz08GGKw+39QGG5yt3BsSK51cCPnE1hx/DLACy373vC6rBtYXh4o//1MSQ1pcME4U1OtQ+NXGrQRgK8zasiqzHJTWZUcseuTXsoIRuKR1pKol+2zZRMB5Lj9c7bLYXlzzJ5wszjrm1dUttUnP7CglMyckygWglWNupfhVCRsRVEylK5ehFZIJxxvVBrHqDmUJRrLXCyxi4M365gM8kQET0yMAM+hbhJQP+72vgw7DOuWRd8iW6X2hUIrh988K9rtOG1C6B+evrFF/izyc8rrQUX2pqe6/+gpEkjFBYP5gUhVcOn8YPVxJxBgtym7nXvNt86r0WMvzRh5wlNlQ7jHqfyj6J9lVbVqwRot6KwLE4VB/0a1iA4ObqbuUSvGUayoq7kybz06QD9l5DLw96nfJ+Oa14RKEjvzED6XfxkwldB6FJJdvfiYM5Wovo1NnFsLYfgZcxh1Dng8btbRFAca5KONV5O8JI
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
