---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAqTFtxuYhUoztqXHeXUqLPuD+kDvzmMw8ZGWDolqIxsq+WPsryNYQFJoo1+z7yYjQ9Rdjkgl4xITQ8ssCLojj6ao5wQguxOIAikR1CWgKx1pPDXqtvj1IECEWeitfBHPY+4dIR5EgLSWXjPZhOZBzK+7crByWa4MGzTuZ1M4r/quIHEWwEP9jnUmog0ivIOimZkVR1U3wmMUyQ+ouWVKX1LJ6ju2Xl+qZ6BL+2G+aTQYzgZ/tfhAFVRXecMNo744J4oH1wceWXdBCi9h0pWTmiEWi3WWalKhLgyCos9xGzwE4peVunBSxH0OOammrWLbQkNAznFp2g3m6UJnbDwGoPqWFieHvbK1takfnxGN2WImLpMOLUdVGrynNdorSkJ2jgWCSXYVg75J13tZ1IediWtmbrhRWGR/hjJ5oTuYzuSD4ZDgqrqHe0/cVPCK2LMp8reoB5ilSc7JeapYfOfTQBeW6yIQGv4DvAG080neRjKBhVW/TgSLGMBKOF6KH79OlMjummE9hMkLzvJvcpWDwgrSvV6ifeQuo1LJaGUWaYqXUA6zLwL6HqE2WLn30tlQwAlbqPMViQSvC1CjXDoEnmfveyiRQgslt9FZ/m/aeu4AtxU1Lbf0dC8JKcyT6/xxJ43QTUrzTt9gdLVhqmDfM2pRr8IP8u6pFL0pri54g7Wdmkja9h+7xyW8xQQvqTUoAfu8AFUJ2YyQmmfpP7VAZZRhpEQbJUIRdC7GVeJGrRHzDbndW7Fkf5QtLhhnzwBFjDHX157w==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
