---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgASCM0Azxoj7ngOpkr1RfpDhSm0EZDLW85Ya8l3Fcf24xi8itr1B6M/7LcHLeOvULuG5uhxNgG1tSiwuQmyJZWjtxpgVX66O2gDgUu9yiJ/JPv4DXLndYNB4d/sLxetAIvvkrkE0HueKEvNulTK0cvtL3e0DQNhYlPu8C5k4G/aqe+u6N+/KXXV35ivCQqftnnVhkyK1foopQC1mQ6A7JMO3PxhllhGlQll63xkYJrUmLC6e8eB5m04m7H9DFLq37NSOCJDo6N6uYUXQNF0xpkL5VeQhElCiv1KfQZ6Ij8w5x1ob9q1a8krcUdChKSdtkiFV/5GDAW2JLiMEtSUl4ciUTeLJV09BQwj0N13BNMlfcGpTBep5eZJ51sPVtSoPx0UcJnyz7ZOJXoApNiVeW/ypP1MRG2mmr8ycY/YMRp+o8udU8d5zNNFmPlQCYZnfVyvDmuBPhXvgDSAyCaeA1eUMuhXY6+raMzz/ssY7kpZYkVkNtiC0zNdLjmcHh/9aVarhsbuFpMzuIfoX9QIU9nXrpLrZtA39x3nVvpfnuyWtYDRmSGmprdY3pH7CT484AaatUQjZb9DEsXu6ii9JrOKxq0azc82OehPocYQN+59QeIw/W6+EklwqV7+7f9XcYBr8BUkiWOcj58Yb6Dekvka4PFPRldc5iFVGax5rrCCwKJpJzaUXYtXwCg24bXK9JSNf/WVT/PQAkyLX5SSgZ48d5uOV/Abc64lxGyYewC8sxyHGurmNhSnYa1C67cQFaJNAJ9c4A==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
