apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qb-config-pvc
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M # #   REPLACE_ME 根据你实际使用的大小替换 qB 配置文件主要是种子信息，2G 足够