---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBXhxJkxY3w6m7RzS57O1op9QNoSS6XJcEMd984bLGgfvrhItGTGnqBGwRs2CO9388RqYPXU0GFfqnPIBFct1K0Mq5s27dbbNx66bDmTcJ+5HrSC9//lktUWsVUdDS1KZUmEFyUMwt3tyQtgj5HKWHy3BKh1/FDCWF2ZSzoYIp6S9o7UgCHnJc8kqkThIYb4AcWoR+70ioG+5wsc5SfjZgaKMkvBkkPg1zofOeDgPfpJJxLvj+8JBjpqaNW6Wcr8UjX2goYFRxxaVSzRYdhFOdgn4x+WUVdB+TCVvovgnl7GMy+WDzSiHz/dJOadzUuVF0eaM9xZaSy2Eo4/qTHFEzuzTS/JmlY+tzmuehgDIJaxCBcCvQoMWqDRjkR7/cc2zUHpMfQ422L7DGPCnnsLiMOQlj9j48OYULQjCGSVNWDSptuqYJdCnYR5mRAXX82TSSr5JoqAqgDzLtv2gQh08Pkkc6sGM8nInNTF+ZGc3vxz1nuJ1xTzwzXPb08/tcg48TRoRHLdHY6YOiUs1T58jRQZYkw1RmME28KSSLsHFm7ikyd++ujCXlhCVzEsjfU7Y/q9Ocfzva9V6A0dMIO+L/C0P23+7Rx6xuDY0ueE5r4Y3o5wPWjBLGjjkb/6lCVYaT8igxsNLOjqR4CduczNB6qiG2A+MzdAGYY+v/KnC8CLKS1pkHbxwKyE9ocRTbxG0okHEmhrZ5U1Fi2rVk+2b16IDnm/qbRXCByCwzY8fELohExeKLKckwMfav5dwyxd36hEvJh92LeptlawtzwoCTsOrF5UYyVdmoGanDkqyHz9Ij7JYS/azYtRFxYOynBg1aYG7bql08eysYy5qaO6WdQ2620gfC8PjFLw4jQX5o7luMlw4txjtyqCs0ceznIiaMOXTJvuaKB0nQH3W2vTjZ6kPVTvAa5C32cb3FkxZLGjk+vlUqoERfS
  template:
    metadata:
      name: cloudflared-token
      namespace: default
    type: Opaque
