---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: traefik
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAo07jK4HqMS3OZ46P9MtolnwqMRVYp0gFcTryRakx7YxnPySw1gmePiZNlsEIthP3ZKddlAveuOCQ5PvLdhH15G0jGxQ6FcEW2+TbYQzw3P1snNZifyFuMvrf6bgZFcLbwEmY4147+voTkGgvqAYmgQKqfBd/RYdeGWV9t8zhtpfkDswPkGfe7vEXyNbvCGFmaRKUKGZOwVH/VzLnNd4TrqNWaybrOUzuALo5D7X0F7Kmw5qQWaCnRbCaw2riSZ6WQJhTrTxqwnm2vMXnnP+xEkHG4+189uYiinbjDBjXCWi7EcKDmiho67KTuLJ6i3+j9VUFO/tTOlqIRIPIyjlMkhC821J16UnpFvq21GSHB6iQQieRs7UoUT3kgAd6LsjZH5uOP3ZLpvAPFB3f2JIlEyoQxxdKvNp5XUpd5MhIrBOJWJgjaAfOTUOGt2+5vQyWrKBla/iNX38CGhLJuzRzxPZdt6WGRIF38e5jSHBl2vYFwg2RF84xfLESS7bKQK2WJ071UOnOIZLfFBiTRKuxIwcPrHrDdkVpbh3M48OieV1uSOrHKcqzmh/4D/Jrsf8ZEf6NAVUT98mbMSWa5pPThaPMDEmhoJW/V0pC3F/sPPaiWazPR7DBRK4muHDZRVZYV9NbFwHb352HOZLelQYSQex/5wjOLmyO9rFJScRAW7T9WVe6J6PFs16f7qL0I4jW90Yp29Pzmo+efqanV02z8d/u5ODqmx9EYrcXVYkKWr4ykXZ8nwCbnvaLELIKpTF6w6F9mK3G0fTBfdbAhyd61VX6Hns2m/VxPgzaIwUUEj+b6ZnU+Yt8spSs03o+yJXaG9XRxJtRy8JXoYEunqBRYIag4RUkzlH117cNFE2wMh6M5PlQ4C2nF8tqDBR3GztAU9pPbDAG94VDDbsvupzNpdfvDUSnJsN943vNGTMR7Jd4z6UwAgoL1
  template:
    metadata:
      name: cloudflared-token
      namespace: traefik
    type: Opaque
