---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCD/LPgd0s/PMhqa5aAn1eEKNBLNVhTk5D9NIuFZVUBaWxcgSC9pcDNAvzy2SJDgmaJlkV4BOZMdLIy+m9ZtPgC0jQLymMcl3WYZm0cYrl31AFUAB85S09fNpiYTe1aw1kRfC+fslAv5cDwkOB6djq7jKjv9gI/Hv5PRQaKxV+lQbD7bDwOVKvQvpxkN8JjqdukQ2chpgIRlteoSMThcTTlvCvXXtlTAXXkRFmDnooEMIJdNJRREAohlP+DIJcR3yMX0/YYDYXS7MSPes52hswknZxmZZbI6x+RdfXHt0Sxbo3QsriNV1T2a/NXci3w6fS7mtEzfb04SyFdmEYwzPsAb06x3Jmhf6Vk2yrcY1rzT4hzvNQ45MYc5kNjXLAKWlmDjyhP9tUAqTKgTpJxjKA1yyj87TnP6mXr/lvAYfHGlM/EBf3RtN1q+O7nk+cpZz3L10yePNfE6IJVl4jr+VHuCYMa6TU7aBgf0A3wuBigmaQUp0iTgO3/Etz5Ztvzk35LauMfY463CUY8tawEo9j7Wr5qzfzXHiadQPV4xuVBlRCWOPL6VPKQ5/R1Uk8iMtLL7kkeqclBmrSsLNB18mFeFsnc+z7Vs5Jvww2MCJSAZ4kukFs6tsBVSz9ZkF6VSc/6x3kr1RUfwroPNsnn7QmyUb06ddWe2Q3ln4XYqDxLl4Q7kji/KtcXNnmjAH6sfYE6NCa2qRLNYqJSMEDy7X1A4vhSAKUM2Fom72Wsn2A6jb9pBxIFJCArYdtd5xNT7BtG42WTelvn5QNNV9bIsEX39DH277z9I9GjUTTGGhSJoF85SQqF7cJYDXdTCaUS7icuROWKZ/ZKScGVU+A4rUwDNy/UYEyHRQ7xPAHADjTgVX2aINLXUOXPPWMsEWzCOKCep0zeSY2iH7Di1Mq/DS+yewm0QBVLvrC0SttII1OCoakXHLwVz6oR
  template:
    metadata:
      name: cloudflared-token
      namespace: default
    type: Opaque
